Hello Microverse Template
Div685/hello-microverse pull request #1
Opened 2022-04-13 21:08 UTC by Div685

- Added HTML and CSS files

2022-04-14 11:05 UTC, MrRamoun requested changes
# 🟠 Project Invalid! ⚓

## Hi @Div685  👋

While you made a great effort in this project that I really appreciate 🙇, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that did not pass **all** linters' checks. Please, try to make sure your repo has no linter errors.

Your Code Review Request will be marked as **invalid** in your Dashboard. Don't worry though, You still have **3** More attepmts. So please submit a new one once you are ready 🙏.

_Cheers and Happy coding!👏👏👏_

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [![@ramoun16](https://img.shields.io/twitter/follow/ramoun16?label=ramoun16&style=social)](https://twitter.com/ramoun16)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-15 12:19 UTC, MrRamoun requested changes
# 🟡 Almost There! 🏃

## Hi @Div685  👋

### Welcome to Microverse! 🌎

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues that you still need to work on though to go to the next project but you are almost there! 🏃 

### Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

I am going to guide you on how to fix them down below. 🤓

## Highlights 🌟

- ✔️ descriptive commit messages
- ✔️ Use of semantic HTML
- ✔️ The code is top-notch! 💯 and have a huge potential.

## Required Changes ♻️

- [x] [REQUIRED] You should make sure that your pull request description is descriptive before review. For example, you can mention what features and files you added instead of just mentioning the entire project.

_Check other comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [![@ramoun16](https://img.shields.io/twitter/follow/ramoun16?label=ramoun16&style=social)](https://twitter.com/ramoun16)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 12:19 UTC, OmarRamoun commented on README.md
> +e.g. `$ git clone https://github.com/Div685/hello-microverse.git`
- Your Steps are very descriptive 📓  and easy to follow. That is really impressive 👏 .

2022-04-15 12:19 UTC, OmarRamoun commented on index.html
> +  <h3>Hello Microverse!</h3>
- [x] [REQUIRED] please, use an `<h1>` tag instead of `<h3>` tag as mentioned in the [requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) of the projects

2022-04-15 12:19 UTC, OmarRamoun commented on style.css
> +  /* background-color: azure; */
- [x] [REQUIRED] 👍 it would be better to remove commented code entirely and use git history to see old code. Because it is going to pollute the codebase  (for more information, read [this article](https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Fbetterprogramming.pub%2Fto-comment-code-or-not-to-comment-code-that-is-the-question-e6a4801fea7e#:~:text=The%20outdated%20comment%20gives%20a,itself%2C%20which%20is%20already%20obvious./m/global-identity?redirectUrl=https%3A%2F%2Fbetterprogramming.pub%2Fto-comment-code-or-not-to-comment-code-that-is-the-question-e6a4801fea7e#:~:text=The%20outdated%20comment%20gives%20a,itself%2C%20which%20is%20already%20obvious.)), please consider removing them.

2022-04-15 12:19 UTC, MrRamoun commented on style.css
> +h3 {
- [ ] [REQUIRED] can you please use a class-selector instead of an element-selector. As required in the project requirements.

2022-04-15 12:57 UTC, Div685 commented on README.md
> +e.g. `$ git clone https://github.com/Div685/hello-microverse.git`
Thank you @MrRamoun.

2022-04-15 15:14 UTC, Div685 commented on style.css
> +  /* background-color: azure; */
Thank you @MrRamoun, I didn't notice the commented code and the article is really helpfull.

2022-04-15 18:37 UTC, MrRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @Div685  👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse.

Finally, you did it! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Software Engineer ⛑️.

There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [![@ramoun16](https://img.shields.io/twitter/follow/ramoun16?label=ramoun16&style=social)](https://twitter.com/ramoun16)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 17:51 UTC, merged